name: "sampler"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
    - apt-cacher-ng
    - selenium

  apt-cacher-ng:
    image: sameersbn/apt-cacher-ng
    # container_name: apt-cacher-ng
    ports:
      - "3142:3142"
    volumes:
      - apt-cacher-ng:/var/cache/apt-cacher-ng
    restart: unless-stopped

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped

volumes:
  apt-cacher-ng:  
